### ISSUE TITLE
Malformed output

### ISSUE THREAD

**Issue by jaanos** [ninastempelj/SAT_Solver#1]
In your output, you are using tildes (`~`) to denote negations. Please change them to minuses (`-`) to comply with the DIMACS format.

Also, I've tried running your program on the `sudoku_mini.txt` example input, and the output file does not correspond to a satisfying valuation of the input formula - in fact, it seems that one variable is missing from the output. So I'd suggest that you also look into this.

**Comment by ursa16180** [comment]
Our example input is `testGraph.txt` as described in README.md and not `sudoku_mini.txt`.

**Comment by jaanos** [comment]
Thanks, the output is now in the correct format, but the solution for `sudoku_mini.txt` is still incorrect.

Note that I have run all submissions on `sudoku_mini.txt` to see if I am running them correctly and to catch obvious errors like this. The file I have [linked to](https://github.com/jaanos/LVR/tree/master/homework/2017/dimacs) is `testGraph.txt`, as you have specified. I will make the test runs on each team's example inputs in the next week.

**Comment by ursa16180** [comment]
Thank you for help. We have corrected the mistake, but manage to not merge correctly. I hope now we have uploaded the correct version.
Are we allowed to make any improvements until next week?

**Comment by jaanos** [comment]
Thanks, I've now updated to your latest commit, which now works correctly on `sudoku_mini.txt`.

You can make changes until the end of the week - please let me know when you want me to update the link (preferably by opening an [issue](https://github.com/jaanos/LVR/issues) on the course repository).
